### ISSUE TITLE
CI server http proxy is missing alternative serverNames

### ISSUE THREAD

**Issue by tnozicka** [redhat-kontinuity/catapult#105]
While merging https://github.com/redhat-kontinuity/catapult/pull/100 someone probably forgot the instruction: `Also add jenkins.master.10.3.10.147.xip.io as an alternative serverName to http proxy server.`

Please add:
 - jenkins.master.10.3.10.147.xip.io
 - jenkins.master.10.3.10.147.nip.io

as an alternative serverNames to http proxy server or users will get:
```
503 Service Unavailable
No server available to handle the request.
```

**Comment by ALRubinger** [comment]
A task for @sabre1041 I think, and likely not really to be charted here as it doesn't pertain to repo code, correct?

Config issues are handled at: https://trello.com/b/iv4wARaG/kontinuity-ci-environment

Andrew/Dharmit, mind looking here?  Or is the new environment close enough that we won't spend time in config of the old one?

S,
ALR

**Comment by sabre1041** [comment]
@ALRubinger I added routes to OSE environment for both Jenkins and Nexus to be resolvable using `xip.io` 

* `jenkins.master.10.3.10.147.xip.io`
* `nexus.master.10.3.10.147.xip.io`

**Comment by tnozicka** [comment]
> @ALRubinger likely not really to be charted here as it doesn't pertain to repo code, correct?

OK, I have put it here because it was coupled with the PR updating docs. I will use Trello next time.

>@ALRubinger I added routes to OSE environment for both Jenkins and Nexus to be resolvable using xip.io

Thanks.
Works for me => closing this.

**Comment by ALRubinger** [comment]
Awesome all, thanks!
