### ISSUE TITLE
Catapult Web Application Cannot be Deployed to Wildfly OpenShift Image

### ISSUE THREAD

**Issue by sabre1041** [redhat-kontinuity/catapult#110]
The `openshift/wildfly-100-centos7` S2I builder only contains logic for a single module maven build. Since this repository is a multi module maven project, when deploying to OpenShift, the .war deployable artifact in the `web` module cannot be deployed.

**Comment by ALRubinger** [comment]
eb7e9495901c7419ae4f496dd1cbd830156a9f66
