### ISSUE TITLE
Lock down on formatting

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#113]
- Add formatting templates to the repo for Eclipse/IDEA (check out examples in ShrinkWrap)
- Apply IDEA .editorconfig to the project
- Mass format
- Enforce in the build using CheckStyle

**Comment by ALRubinger** [comment]
BTW it's going to be spaces, not tabs.

**Comment by sabre1041** [comment]
@ALRubinger brilliant!

**Comment by ALRubinger** [comment]
1f3af7b120bfb0711109829f7ecc440f141ee905 #173
