### ISSUE TITLE
Embed the project template

### ISSUE THREAD

**Issue by xcoulon** [redhat-kontinuity/catapult#125]
Instead of having a single, large template to create all project resource, we can rely on a smaller `Jenkinsfile` along with a `deployment-template.yaml` at the root of the GitHub repo to clone.
The remaining part is a generic template that creates a build configuration with a Jenkins pipeline strategy.
This template can be embedded in the Catapult application.

**Comment by ALRubinger** [comment]
Addressed in PR #127
