### ISSUE TITLE
Trigger a first build upon fling completion 

### ISSUE THREAD

**Issue by xcoulon** [redhat-kontinuity/catapult#128]
Create a new `Build` resource from the generated `BuildConfig` resource in the OpenShift project.

**Comment by tnozicka** [comment]
Would adding this trigger (https://github.com/tnozicka/openshift-templates/blob/master/pipeline-template.yaml#L34) be enough?

**Comment by ALRubinger** [comment]
PR submitted: https://github.com/redhat-kontinuity/catapult/pull/132

**Comment by xcoulon** [comment]
@ALRubinger thanks, I actually forgot to link the PR to the issue here.

**Comment by ALRubinger** [comment]
6d85abfc3440d379e7135325f7005bbf4b80e57c
