### ISSUE TITLE
Webhook trigger is incorrectly set 

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#141]
We're setting the webhook trigger by the `CATAPULT_OPENSHIFT_API_URL`, which in the case of Catapult running inside OpenShift (in a container) is:

`https://openshift.default.svc.cluster.local`

This results in a webhook like:

`https://openshift.default.svc.cluster.local/oapi/v1/namespaces/jboss-eap-quickstarts/buildconfigs/helloworld-pipeline/webhooks/kontinu8/github`

Probably what we need to be doing is setting this to the externally-accessible URL, `CATAPULT_OPENSHIFT_CONSOLE_URL`

**Comment by ALRubinger** [comment]
3a673b0 FYI @xcoulon 

Also I did some minor redesign to ask the service about the correct URL, not the project. (Project is just a dumb value object, and the service shouldn't probably be reporting out its internals like target URL in the API).  WDYT?

**Comment by xcoulon** [comment]
@ALRubinger thanks for fixing this, and yes, the design is actually much better this way !

**Comment by ALRubinger** [comment]
@xcoulon OK thanks for reviewing!
