### ISSUE TITLE
CORS issue when accessing AppStore URL 

### ISSUE THREAD

**Issue by gastaldi** [redhat-kontinuity/catapult#152]
The following error is shown when the app is accessed in Firefox: 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://raw.githubusercontent.com/redhat-kontinuity/appstore/master/appstore.json. (Reason: CORS preflight channel did not succeed).
```

**Comment by ALRubinger** [comment]
Seems to be fixed by nature of not letting the client directly get to the catalog URL, but instead having the server proxy the request.  Pending @gastaldi response on whether we need CORS filter as currently in 40818f3

**Comment by gastaldi** [comment]
The CORS filter is needed for external clients looking to consume our JAX-RS endpoints. If there is no intention to have consumers of our API outside the WAR file (e.g. consuming the AppStore JSON in a web page) then I agree we don't need it.

**Comment by ALRubinger** [comment]
Ah, that makes sense.

Yes, we'll likely have web clients consuming this which aren't originating
from the Catapult app.  So we'll leave the filter, thanks.

**Comment by ALRubinger** [comment]
7c90f05aac62b4c7bbc888e1bb123df9e2d2f531
