### ISSUE TITLE
Use global superuser (admin) to create OpenShift Projects on behalf of users

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#18]
Currently we log in and make projects _as a_ user; instead we really need to, as an admin, make projects _for_ users and grant them access.

**Comment by ALRubinger** [comment]
Existing code in question in `Fabric8OpenShiftClientServiceImpl`:

`final Config config = new ConfigBuilder().
                withMasterUrl(apiUrl).
                withUsername("admin"). //TODO externalize or account for this?
                withPassword("admin"). // TODO externalize or account for this?
                withTrustCerts(true). //TODO never do this in production as it opens us to man-in-the-middle attacks
                build();`

**Comment by pmuir** [comment]
I can take a go at this tomorrow.

**Comment by pmuir** [comment]
I made a start on this, and I think the answer is to create a rolebinding from the user(s) to the project. This means I will need to alter the OpenShiftService to look like

```
public OpenShiftProject createProject(final String name, List<String> userNames) throws
            DuplicateProjectException,
            IllegalArgumentException
```

At the moment I'm not sure on a couple of things:

1) How I would log in properly as the cluster-admin
2) How I get a list of role refs to bind.

**Comment by ALRubinger** [comment]
TBH I'm learning as I go to so don't have insight offhand, but hey sure run with it! :)  I'll take over if you get stuck/busy.

**Comment by ALRubinger** [comment]
Maybe just a bit more clearly:

```
public OpenShiftProject createProject(final String projectName, String... userNames) throws
            DuplicateProjectException,
            IllegalArgumentException
```

**Comment by ALRubinger** [comment]
ALR needs to open a discussion on this to kontinuity-dev-public and work through some technical and logistics stuff with Clayton; we will never get cluster-admin rights on Online.

**Comment by ALRubinger** [comment]
Discussion thread on this https://www.redhat.com/archives/kontinuity-dev-public/2016-April/msg00003.html

**Comment by ALRubinger** [comment]
Resurrected.  Going down the OAuth route by nature of creating an OAuth client as cluster-admin for the Catapult application.

```
oc --config=openshift.local.config/master/admin.kubeconfig get oauthclients -o yaml

oc --config=openshift.local.config/master/admin.kubeconfig create -f <(echo '
kind: OAuthClient
apiVersion: v1
metadata:
 name: redhatdevelopers-catapult-local
secret: 3f23735ce5984601fcb93c5c3ecf4b71d7c8cbfa 
redirectURIs:
 - "http://127.0.0.1:8080/api/appstore/applications" 
grantMethod: prompt 
')
```

**Comment by ALRubinger** [comment]
https://docs.openshift.org/latest/rest_api/index.html#rest-api-index
https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#oauth

**Comment by ALRubinger** [comment]
Now we handle this by getting auth from the user and using the user's token to execute on the OpenShift API
