### ISSUE TITLE
Describe scopes needed for access token in README

### ISSUE THREAD

**Issue by pmuir** [redhat-kontinuity/catapult#22]
Add to the README in the project root the scopes we need to enable when creating the GitHub personal access token.  Screenshot below shows the scopes to enable; this task is just about documenting it.

**Comment by ALRubinger** [comment]
Reason I can see to justify this: We'll be using the tests to automatically grant the app permission to act on the user's behalf in these scopes, so let the developer running the tests know upfront what they're agreeing to.

**Comment by pmuir** [comment]
I meant - when I complete the action described in the README, it asked me what scopes to grant. I didn't know which ones to pick, if any.

**Comment by ALRubinger** [comment]
Ah I see what you mean; in creating *your client secret*, not in Scott's OAuth WebFlow.

Got it and will do.

**Comment by ALRubinger** [comment]
Scopes needed:

![screenshot1](https://cloud.githubusercontent.com/assets/199891/14368615/de1bdf1e-fcec-11e5-91d1-f65de6e4f739.png)

**Comment by ALRubinger** [comment]
Let's see if the community wants in on this one: 

https://twitter.com/ALRubinger/status/718201180791402496

**Comment by ALRubinger** [comment]
22de22d6aa245251aedaaeaaa514eedec83ed425
