### ISSUE TITLE
Specify in more detail how origin should be used

### ISSUE THREAD

**Issue by pmuir** [redhat-kontinuity/catapult#23]
The linked page on openshift origin offers a few options to get started, be more explicit about which one.

**Comment by ALRubinger** [comment]
To be clear: it's really any of them.  Let's make that explicit in the docs, but any way you get OpenShift running locally should be fine.

**Comment by ALRubinger** [comment]
e52f8dc49c9e92ba680faeb4faffcaadf9b252c8
