### ISSUE TITLE
Refactor GitHubServiceFactory as an EJB/ CDI bean

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#41]
Let's get rid of a lot of the custom ServiceLoader code and rely upon the container to inject an instance.

Tests should be done in stages: a base that has an extension to provide the GitHubServiceFactory as a POJO, and another test to run against the container getting the GitHubServiceFactory injected as an EJB or CDI managed component

**Comment by xcoulon** [comment]
Could we replace this `GithubServiceFactory` from within the API with a CDI Producer that would take the GitHub token and username as parameters ? We could keep the same `create(String, String)` signature for the method, by using custom CDI annotations (eg: `@GitHubToken` and `@GitHubUsername`) along with producer methods for those items. If that make sense, I can try to work on it.

**Comment by ALRubinger** [comment]
Actually I was thinking we add a CDI/EJB layer on top of the POJO stuff to
keep us with:

1) Unit tests (POJO based as-is)
2) Integration tests using WildFly directly
3) Full integration tests against the Docker image w/ WildFly and our app
running inside

So likely I should / you could update the issue to reflect that, unless you
have strong opinions otherwise?

**Comment by ALRubinger** [comment]
Upstream: 
b984ec7c25fac1f51e0ffe2aedd4641f79372fe3
c4e2a711971232272de4c916ca2950d21a6f6f77
