### ISSUE TITLE
Refactor OpenShiftServiceFactory as an CDI 

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#42]
Let's get rid of a lot of the custom ServiceLoader code and rely upon the container to inject an instance.

Tests should be done in stages: a base that has an extension to provide the OpenShiftServiceFactory as a POJO, and another test to run against the container getting the OpenShiftServiceFactory injected as an EJB or CDI managed component

**Comment by xcoulon** [comment]
@ALRubinger I could probably look at this issue since I worked on #41 last week.

**Comment by ALRubinger** [comment]
Definitely. let's do it in similar fashion to how GitHubService is now

**Comment by ALRubinger** [comment]
a63338fda57172ec50869c03127468d5b1f7ce18
