### ISSUE TITLE
Create SPI for GitHubService

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#61]
To support:

* Deleting a repository
* Deleting a WebHook
* Creating a repository

...to be used in testing

**Comment by ALRubinger** [comment]
Example of an SPI is in OpenShiftServiceSpi

**Comment by xcoulon** [comment]
@ALRubinger I'm just just landing here and I'd like to clarify something: do you want to a new GitHubService implementation or a GitHubService implementation based on the  `KohsukeGitHubServiceImpl` class ?

**Comment by ALRubinger** [comment]
c05d9f22716d3f30184cb24a116d545608b54165
