### ISSUE TITLE
Refactor the GitHubServiceProducer into an injectable GitHubServiceFactory

### ISSUE THREAD

**Issue by xcoulon** [redhat-kontinuity/catapult#81]
The `GitHubServiceFactory` should be injectable, and should provide users with a `create(String)` method that would take the GitHub token passed into the `Projectile` to instanciate a new `GitHubService` in the user's context.

**Comment by ALRubinger** [comment]
This factory should be part of the API, unlike the Producer which is part of the impl.

Part of this issue: apply the refactor to `CatapultImpl` to inject the factory

**Comment by xcoulon** [comment]
Good point, indeed.

**Comment by ALRubinger** [comment]
db6bf0d
